// Class bestand, dus geen component!
// Naamgeving MOET overeenkomen met naamgeving backend (getters/setters -> postman)
export class Book {
  id?: number;  // ? heeft te maken met autogenerated id
  title: string;
  year: number;
  isbn: number;
  origin: string;
  remarks: string;
  checked: boolean;
}