// Class bestand, dus geen component!
// Naamgeving MOET overeenkomen met naamgeving backend (getters/setters -> postman)
export class Writer {
  id?: number;   // ? heeft te maken met autogenerated id
  firstName: string;
  lastName: string;
}