// Class bestand, dus geen component!
// Naamgeving MOET overeenkomen met naamgeving backend (getters/setters -> postman)
export class Genre {
  id?: number;  // ? heeft te maken met autogenerated id
  genreName: string;
}
